# Generated by Django 4.2.5 on 2023-10-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('preview', models.CharField(max_length=250)),
                ('full_view', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images')),
            ],
        ),
    ]
